name: CI - Build & Test
on:
  push:
    branches: ["main", "develop", "feature/*"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build-test:
    name: Build & Test React App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9 # Chọn version pnpm bạn đang dùng (VD: 8 hoặc 9)

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: pnpm install

      - name: Run Linter & Tests
        run: |
          pnpm lint
          pnpm run --if-present test
      - name: Build Test Docker Image
        run: docker build -t react-fe:test .
